trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'


steps:
- checkout: self
  persistCredentials: true
- task: TerraformInstaller@0
  displayName: "Install Terraform"
  inputs:
    terraformVersion: '1.3.9'
    terraformDownloadLocation: 'https://releases.hashicorp.com/terraform'
- task: TerraformInstaller@1
  displayName: 'Terraform Init'
  inputs:
    command: 'init'
    workingDirectory: '$(Build.SourcesDirectory)'
    backendType: 'azurerm'
    ensureBackend: true
    backendServiceArm: 'mt-dna-ent-dataplatforms-nonprod (ae9ff6a8-2caf-45d6-86c7-64f8fa1bf196)'
    resourceGroupName: 'rg-dmp-devops-backup'
    storageAccountName: 'devopsstrterraform'
    containerName: 'terraformstatfile'
    key: 'tf/terraform.tfstate'